config/routes.rb
Rails.application.routes.draw do
  root "servers#index"
  ActiveAdmin.routes(self)
  post '/contact', :to => "application#contact"
  get '/tag/:tag', :to => "servers#index", :as => "tag"
  get '/version/:version', :to => "servers#index", :as => "version"
  get '/country/:country', :to => "servers#index", :as => "country"
  get '/api', :to => "resources#api", :as => "api"
  get '/terms', :to => "resources#terms", :as => "terms"
  get '/stats', :to => "application#stats", :as => "stats"
  get '/user/:username', :to => "application#user", :as => "user"
  get '/favorites', :to => "application#favorites", :as => "favorites"
  post '/search(/:search)', :to => "servers#search", :as => "search"
  get '/countries', :to => "application#countries", :as => "countries"
  get '/tags', :to => "application#tags", :as => "tags"
  get '/versions', :to => "application#versions", :as => "versions"
  get '/sponsored', :to => "application#sponsored", :as => "sponsored"
  get '/resources/sponsored', :to => "resources#sponsored", :as => "sponsored_resource"
  devise_for :users, :controllers => { :registrations => "registrations" }
  resources :servers do
    resources :comments
    resources :reports
    resources :favorites do
      post :favor
    end
    post :cast_vote
    get :vote
    get :banner
    get :embed
    get :display
  end
  resources :revisions
  resources :articles
  get 'ping' => proc {|env| [200, {}, []] }
end

app/models/article.rb
class Article
  include Mongoid::Document
  include Mongoid::Timestamps
  validates :text, presence: true
  validates :title, presence: true
  field :text
  field :title

  belongs_to :user
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  before_filter :require_admin, except: [:index, :show]
  def index
    @articles = Article.desc(:created_at)
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.create(article_params)
    @article.user = current_user
    if @article.save
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  private
  def article_params
    params.require(:article).permit(:text, :title)
  end
end

app/views/articles/_form.html.haml
= form_for(@article) do |f|
  = render 'partials/errors', object: @article
  .row
    .col-md-12
      %p
        = f.label :title
        %br/
        = f.text_field :title, class: 'form-control', style: "width: 45%"
      %p
        = f.label :text
        %br/
        = f.text_area :text, class: 'form-control wysihtml5', rows: 15, style: "width: 75%"
      %p
        = f.submit 'Submit', class: 'btn btn-primary'

app/views/articles/edit.html.haml
- content_for :title do 'Editing Article' end
- content_for :head do
  %meta{:content => "Editing Unturned ServerZ Article", :name => "description"}
  %meta{:content => "Servers, Unturned, Article, Edit", :name => "keywords"}
.page-header
  %h1 Editing Blog Post

= render 'form'

app/views/articles/index.html.haml
- content_for :title do 'Blog' end
- content_for :head do
  %meta{:content => "Unturned ServerZ Blog", :name => "description"}
  %meta{:content => "Servers, Unturned, Blog, Dev, Updates", :name => "keywords"}
.page-header
  %h1 
    Blog Posts
    - if current_user
      .pull-right
        = link_to 'New Article', new_article_path, class: 'btn btn-primary'

.row
  .col-md-12
    .text-center
      .alert.alert-info This blog is for information regarding updates to both Unturned ServerZ, as well as updates the to the game. Some blog posts may also contain content relating to the Unturned community!
    %hr
    - @articles.each do |article|
      %h2
        = article.title
      .well{style: "margin-bottom: 0px;"}= simple_format(article.text)
      - if current_user.try(:admin)
        %a.badge.badge-primary.pull-left{style: "font-size: 12px; margin-top: 5px;", href: edit_article_path(article)} Edit

        = link_to 'Delete', article_path(article), method: :delete, data: {confirm: "Are you sure you want to delete this article?"}, class: "badge badge-primary", style: "font-size: 12px; margin-top: 5px;"
      .label.label-primary.pull-right{style: "font-size: 14px; margin-top: 5px;"}= time_ago_in_words(article.created_at) + " ago"

app/views/articles/new.html.haml
- content_for :title do 'New Article' end
- content_for :head do
  %meta{:content => "Creating Article for Unturned ServerZ", :name => "description"}
  %meta{:content => "Unturned, Servers, Article, New, Create", :name => "keywords"}
.page-header
  %h1 New Blog Post

= render 'form'