config/routes.rb
Rails.application.routes.draw do
  root "servers#index"
  ActiveAdmin.routes(self)
  post '/contact', :to => "application#contact"
  get '/tag/:tag', :to => "servers#index", :as => "tag"
  get '/version/:version', :to => "servers#index", :as => "version"
  get '/country/:country', :to => "servers#index", :as => "country"
  get '/api', :to => "resources#api", :as => "api"
  get '/terms', :to => "resources#terms", :as => "terms"
  get '/stats', :to => "application#stats", :as => "stats"
  get '/user/:username', :to => "application#user", :as => "user"
  get '/favorites', :to => "application#favorites", :as => "favorites"
  post '/search(/:search)', :to => "servers#search", :as => "search"
  get '/countries', :to => "application#countries", :as => "countries"
  get '/tags', :to => "application#tags", :as => "tags"
  get '/versions', :to => "application#versions", :as => "versions"
  get '/sponsored', :to => "application#sponsored", :as => "sponsored"
  get '/resources/sponsored', :to => "resources#sponsored", :as => "sponsored_resource"
  devise_for :users, :controllers => { :registrations => "registrations" }
  resources :servers do
    resources :comments
    resources :reports
    resources :favorites do
      post :favor
    end
    post :cast_vote
    get :vote
    get :banner
    get :embed
    get :display
  end
  resources :revisions
  resources :articles
  get 'ping' => proc {|env| [200, {}, []] }
end

app/views/partials/_alerts.html.haml
- if notice
  .alert.alert-success.alert-dismissible{role: "alert"}
    %button.close{"data-dismiss" => "alert", type: "button"}
      %span{"aria-hidden" => "true"} ×
      %span.sr-only Close
    = notice
- if alert
  .alert.alert-danger.alert-dismissible{role: "alert"}
    %button.close{"data-dismiss" => "alert", type: "button"}
      %span{"aria-hidden" => "true"} ×
      %span.sr-only Close
    = alert

app/views/partials/_analytics.html.haml
:javascript
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-53945300-1', 'auto');
  ga('send', 'pageview');

:javascript
  (function() {
      function async_load(script_url){
          var protocol = ('https:' == document.location.protocol ? 'https://' : 'http://');
          var s = document.createElement('script'); s.src = protocol + script_url;
          var x = document.getElementsByTagName('script')[0]; x.parentNode.insertBefore(s, x);
      }
      bm_website_code = '73BBF5DF939D4725';
      jQuery(document).ready(function(){async_load('asset.pagefair.com/measure.min.js')});
      jQuery(document).ready(function(){async_load('asset.pagefair.net/ads.min.js')});
  })();

app/views/partials/_contact.html.haml
#contact.modal.fade{:role => "dialog", :tabindex => "-1"}
	.modal-dialog
		.modal-content
			.modal-header
				%button.close{"data-dismiss" => "modal", :type => "button"}
					%span{"aria-hidden" => "true"} ×
					%span.sr-only Close
				%h4.modal-title{style: 'text-align: left;'} Contact Us
			= form_tag contact_path, method: 'post' do
				.modal-body{style: 'text-align: left;'}
					%p
						= label_tag 'Email:'
						= email_field :contact, :email, class: 'form-control', value: current_user ? current_user.email : ""
					%p
						= label_tag 'Username:'
						= text_field :contact, :username, class: 'form-control', value: current_user ? current_user.username : ""
					%p
						= label_tag 'Question:'
						= text_area :contact, :question, class: 'form-control', placeholder: "Enter your question here.", rows: 10
				.modal-footer
					= submit_tag 'Submit', class: 'btn btn-primary', data: { disable_with: "Voting..." }
					%button.btn.btn-danger{"data-dismiss" => "modal", :type => "button"} Close

app/views/partials/_errors.html.haml
- if object.errors.any?
	%ul
		- object.errors.full_messages.each do |msg|
			%li{style: 'color: red;'}
				= msg

app/views/partials/_footer.html.haml
%footer
  %hr/
  %ul.nav.nav-pills.footer
    %li.pull-left
      %a © #{Time.now.year} Unturned Servers
    %li.pull-right
      %a{href: "#Top"}
        %i.fa.fa-chevron-up
        Back to top
    %li.pull-right
      %a{href: terms_path} 
        %i.fa.fa-pencil
        Terms
    %li.pull-right
      %a{href: revisions_path} 
        %i.fa.fa-code
        Revisions
    %li.pull-right
      %a{href: "#contact", "data-toggle" => 'modal'}
        %i.fa.fa-envelope
        Contact
    %li.pull-right
      %a{href: stats_path} 
        %i.fa.fa-signal
        Stats
  %span.st__hcount{:displaytext => ""}
  %span.st_fblike_hcount{:displaytext => "Facebook Like"}
  %span.st_plusone_hcount{:displaytext => "Google +1"}
  %script{:src => "http://w.sharethis.com/button/buttons.js", :type => "text/javascript"}
  :javascript
    stLight.options({publisher: "c2e6e60e-c42d-4a9b-a6c5-0ca8e2f39a96", doNotHash: false, doNotCopy: false, hashAddressBar: false});

app/views/partials/_lowerad.html.haml
%script{:async => "", :src => "//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"}
.row{style: "margin-top: 15px;"}
  .div{align: "center"}
    / Lower Banner
    %ins.adsbygoogle{"data-ad-client" => "ca-pub-4398804065306098", "data-ad-slot" => "4150542567", :style => "display:inline-block;width:728px;height:90px"}
    :javascript
      (adsbygoogle = window.adsbygoogle || []).push({});
    #90ab2f6f32.pagefair-acceptable{style: "align: center;"}

app/views/partials/_navbar.html.haml
%nav.navbar.navbar-fixed-top.navbar-default{role: "navigation"}
  .container-fluid
    .navbar-header
      %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{href: root_path} Unturned ServerZ
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li.dropdown{class: set_active("servers")}
          %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
            %i.fa.fa-hdd-o
            &nbsp
            Servers
            %i.fa.fa-caret-down
          %ul.dropdown-menu{role: "menu"}
            %li
              %a{href: new_server_path}
                %i.fa.fa-plus
                &nbsp
                New Server
            %li.divider
            %li
              %a{href: servers_path}
                %i.fa.fa-hdd-o
                &nbsp
                All Servers
            %li
              %a{href: sponsored_path}
                %i.fa.fa-usd
                &nbsp
                Sponsored Servers
            - if current_user
              %li
                %a{href: servers_path(:owner => current_user.username)}
                  %i.fa.fa-user
                  &nbsp
                  My Servers
            %li
              %a{href: servers_path}
                %i.fa.fa-search
                &nbsp
                Search Servers
            %li
              %a{href: tags_path}
                %i.fa.fa-tag
                &nbsp
                Server Tags
            %li
              %a{href: countries_path}
                %i.fa.fa-flag
                &nbsp
                Server Countries
            %li
              %a{href: versions_path}
                %i.fa.fa-history
                &nbsp
                Server Versions

        %li
          %a{href: new_server_path}
            %i.fa.fa-plus
            &nbsp
            New Server
        %li.dropdown{class: set_active("resources")}
          %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
            %i.fa.fa-book
            &nbsp
            Resources
            %i.fa.fa-caret-down
          %ul.dropdown-menu{role: "menu"}
            %li
              %a{href: 'http://smartlydressedgames.com/unturned/'}
                %i.fa.fa-gamepad
                &nbsp
                Get Unturned
            %li
              %a{href: 'http://unturned.wikia.com/wiki/Unturned_Bunker_Wiki'}
                %i.fa.fa-laptop
                &nbsp
                Unturned Wiki
            %li
              %a{href: api_path}
                %i.fa.fa-code
                &nbsp
                API Documentation
            %li
              %a{href: sponsored_resource_path}
                %i.fa.fa-usd
                &nbsp
                Sponsorship Info
        %li
          %a{href: articles_path}
            %i.fa.fa-book
            &nbsp
            Blog
      %ul.nav.navbar-nav.navbar-right
        %li.dropdown
          %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
            - if current_user
              = current_user.username
              &nbsp  
            %i.fa.fa-user
          %ul.dropdown-menu{role: "menu"}
            - if current_user
              %li
                %a{href: servers_path(:owner => current_user.username)} My Servers
              %li= link_to 'Favorited', favorites_path
              %li= link_to 'View Profile', user_path(current_user.username)
              %li= link_to 'Edit Account', edit_user_registration_path
              %li= link_to 'Logout', destroy_user_session_path, method: :delete
            - else
              %li= link_to 'Sign up', new_user_registration_path
              %li= link_to 'Login', new_user_session_path
      %ul.nav.navbar-nav.navbar-right{style: "margin-top: 5px; margin-right: 30px;"}
        %li{style: "margin-left: 20px;"}
          %a.hidden-xs{href: "http://twitter.com/UnturnedServerz", class: "navbar-brand", style: "vertical-align: text-bottom; background: url(/twitter-logo.png) no-repeat; width: 50px; height: 50px;"}
        %li{style: "margin-left: 20px;"}
          %a.hidden-xs{href: "https://www.facebook.com/unturned.serverz.list", class: "navbar-brand", style: "vertical-align: text-bottom; background: url(/facebook-logo.png) no-repeat; width: 50px; height: 50px;"}

app/views/partials/_servers.html.haml
- if @servers.any?
  %table.table
    %thead
      %tr{style: "font-size: 18px;"}
        %th
          %i.fa.fa-arrow-circle-up
          Rank
        %th
          %i.fa.fa-home
          Name
        %th
          %i.fa.fa-hdd-o
          Server
        %th 
          %i.fa.fa-tag
          Tags
        %th 
          %i.fa.fa-signal
          Status
    %tbody
      - @servers.to_enum.with_index(1).each do |server, index|
        - rank = 1
        - if params[:page]
          - rank = ((params[:page].to_i - 1) * 25) + index
        - else
          - rank = index
        %tr
          %td.text-center{style: "width: 10%; vertical-align:middle;"}
            %strong{style: "font-size: 18px;"}= rank
          %td.text-center{style: "width: 15%; vertical-align: middle; font-size: 18px;"}
            %strong= link_to server.title, server_path(server), class: "server"
          %td{style: "width: 40%;", class: "server-ip-#{server.id}"}
            - if server.banner?
              = link_to image_tag(server_banner_path(server)), server_path(server)
            %a{href: country_path(server.country), id: server.country, alt: server.country_name}
              %span=server.get_flag
            %span{class: "ip", style: "font-size: 18px; vertical-align: middle;", rel: "tooltip", title: "Click to copy to clipboard.", data: {placement: "top"}}
              %strong{id: "clipboard-#{server.id}", class: "clip_button", "data-clipboard-text" => "#{server.ip}"}= server.ip
            :javascript
              $(".ip").tooltip();
            :javascript
              var client = new ZeroClipboard(document.getElementById("clipboard-#{server.id}"));
          %td{style: "width: 25%;"}
            .div
              %a.tag{href: version_path(server.version.gsub(".", "-"))}
                %span.badge=server.version
              - server.tags.each do |tag|
                %a.tag{href: tag_path(tag.text)}
                  %span.badge{style: "margin-bottom: 3px;"}=tag.text
          %td{style: "width: 10%; vertical-align: middle; font-size: 20px;"}
            %span.label.label-warning N/A
  = paginate @servers, params: {authenticity_token: nil, commit: nil, utf8: nil, action: nil}
- else
  #none No servers have been submitted yet.