config/routes.rb
Rails.application.routes.draw do
  root "servers#index"
  ActiveAdmin.routes(self)
  post '/contact', :to => "application#contact"
  get '/tag/:tag', :to => "servers#index", :as => "tag"
  get '/version/:version', :to => "servers#index", :as => "version"
  get '/country/:country', :to => "servers#index", :as => "country"
  get '/api', :to => "resources#api", :as => "api"
  get '/terms', :to => "resources#terms", :as => "terms"
  get '/stats', :to => "application#stats", :as => "stats"
  get '/user/:username', :to => "application#user", :as => "user"
  get '/favorites', :to => "application#favorites", :as => "favorites"
  post '/search(/:search)', :to => "servers#search", :as => "search"
  get '/countries', :to => "application#countries", :as => "countries"
  get '/tags', :to => "application#tags", :as => "tags"
  get '/versions', :to => "application#versions", :as => "versions"
  get '/sponsored', :to => "application#sponsored", :as => "sponsored"
  get '/resources/sponsored', :to => "resources#sponsored", :as => "sponsored_resource"
  devise_for :users, :controllers => { :registrations => "registrations" }
  resources :servers do
    resources :comments
    resources :reports
    resources :favorites do
      post :favor
    end
    post :cast_vote
    get :vote
    get :banner
    get :embed
    get :display
  end
  resources :revisions
  resources :articles
  get 'ping' => proc {|env| [200, {}, []] }
end

app/models/server.rb
class Server
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Search
  mount_uploader :banner, BannerUploader
  before_save :update_vote_count
  before_validation :assign_tags
  search_in :title, :tags => :text
  attr_accessor :tag_string

  validate :tag_count
  validate :check_dimensions, :on => :create
  validates :title, presence: true
  validates :ip, presence: true, uniqueness: true
  validates :port, presence: true
  validates_numericality_of :port
  validates :country, presence: true
  validates :version, presence: true
  validates :slots, presence: true
  validates_numericality_of :slots

  field :title, type: String, default: ""
  field :ip, type: String, default: ""
  field :port, type: Integer, default: 25544
  field :info, type: String, default: ""
  field :country, type: String, default: ""
  field :version, type: String, default: ""
  field :slots, type: Integer, default: 8
  field :sponsored, type: Boolean, default: false

  field :steam, type: String
  field :reddit, type: String
  field :twitter, type: String
  field :facebook, type: String
  field :youtube, type: String
  field :website, type: String
  field :vote_count, type: Integer, default: 0

  has_many :reports, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_and_belongs_to_many :tags, autosave: true
  belongs_to :user

  def self.tag_counts
    Tag.all
  end

  def tag_text
    self.tags.distinct(:text).join(", ")
  end

  def self.valid_tags
    Tag.all.distinct(:text)
  end

  def get_flag
    return "<img src='' class='flag flag-#{self.country}' alt='#{self.country_name}' />".html_safe
  end

  def country_name
    country = ISO3166::Country[self.country]
    country.translations[I18n.locale.to_s] || country.name
  end


  def check_dimensions
    if !banner_cache.nil? && !(banner.width == 468 && banner.height == 60)
      errors.add :banner, "dimensions must be 468x60"
    end
  end

  def update_vote_count
    self.vote_count = self.votes.size
  end

  def assign_tags
    if self.tag_string
      self.tags = self.tag_string.gsub(" ", "").split(",").uniq.map do |name|
        next if not Tag.where(:text => name.strip).any?
        Tag.where(:text => name.strip)
      end
    end
  end

  def tag_count
    errors.add :tags, "are invalid. Use between 1 and 5 tags." unless (self.tags.size >= 1 and self.tags.size <= 5)
  end
end

app/controllers/servers_controller.rb
class ServersController < ApplicationController
	before_filter :authenticate_user!, :except => [:create, :new, :index, :show, :banner, :embed, :display, :vote]
	def index
		@sponsored = Server.where(:sponsored => true)
		if @servers
			return @servers
		elsif params[:country]
			return @servers = Server.where(:country => params[:country]).desc("vote_count").page(params[:page])
		elsif params[:tag]
			tag = Tag.where(text: params[:tag]).first
			if not tag
				return redirect_to servers_path, :alert => "That tag does not exist."
			else
				return @servers = tag.servers.desc("vote_count").page(params[:page])
			end
		elsif params[:version]
			return @servers = Server.where(version: params[:version].gsub("-", ".")).desc("vote_count").page(params[:page]) 
		elsif params[:owner]
			return @servers = Server.where(:user => User.where(:username => params[:owner]).first).desc("vote_count").page(params[:page])
		end
		@servers = Server.desc("vote_count").page(params[:page])
	end

	def search
		query = params[:search]
		@servers = Server.full_text_search(query, allow_empty_search: true).desc("vote_count").page(params[:page])
		return render action: 'index'
	end

	def embed
		@server = Server.find(params[:server_id])
		type = params[:type]
		@text = ""
		@url = ""
		@height = 34
		@width = 191
		if type
			if type == "favorites"
				@url = new_server_favorite_url(@server)
				@text = "Like on Unturned ServerZ"
			else
				@url = server_vote_url(@server)
				@text = "Vote on Unturned ServerZ"
			end
		else
			@url = server_vote_url(@server)
			@text = "Vote on Unturned ServerZ"
		end
		size = params[:size]
		@class = ""
		if size
			if size == "large"
				@class = "btn-lg"
				@height = 45
				@width = 243
			elsif size == "small"
				@class = "btn-sm"
				@height = 30
				@width = 162
			end
		end
		@color = params[:color] ? params[:color] : "primary"
		render :layout => "embed"
	end

	def display
		@height = 34
		@width = 191
		@server = Server.find(params[:server_id])
		@type = params[:type]
		@color = params[:type]
		@size = params[:size]
		if @size == "large"
			@height = 45
			@width = 243
		elsif @size == "small"
			@height = 30
			@width = 162
		end
		respond_to do |format|
    	format.js
  	end
	end

	def show
		@server = Server.find(params[:id])
		return redirect_to servers_path, :alert => 'That server does not exist.' if @server == nil
	end

	def new
		if current_user
			@server = current_user.servers.new
		else
			@server = Server.new
		end
	end

	def edit
		@server = Server.find(params[:id])
		return redirect_to servers_path if not can_manage(@server)
	end

	def update
		@server = Server.find(params[:id])
		return redirect_to servers_path if not can_manage(@server)
		if @server.update(server_params)
			redirect_to @server, :notice => 'Successfully made changes to a server.'
		else
			render 'edit'
		end
	end

	def create
		if current_user
			@server = current_user.servers.create(server_params)
		else
			@server = Server.create(server_params)
		end
		if @server.save
			redirect_to servers_path, :notice => 'You successfully created a new server yet.'
		else
			render 'edit'
		end
	end

	def destroy
		@server = Server.find(params[:id])
		return redirect_to servers_path if not can_manage(@server)
		@server.destroy
		redirect_to servers_path, :notice => "Successfully deleted a server."
	end

	def vote
		@server = Server.find(params[:server_id])
	end

	def cast_vote
		@server = Server.find(params[:server_id])
		return redirect_to @server, :alert => 'You can not vote for your own server.' if @server.user.current_sign_in_ip == request.remote_ip or (current_user and @server.user == current_user)
		return redirect_to @server, :alert => 'You can only vote once every 24 hours.' if @server.votes.where(created_at: ((Time.now - 24.hour) ..(Time.now))).where(ip: request.remote_ip).any?
		captcha = params['form']['captcha']
		return redirect_to @server if captcha != 'zombie'
		@vote = Vote.create(:server => @server, :ip => request.remote_ip)
		return redirect_to @server, :notice => 'Successfully voted.'
	end

	def banner
		@server = Server.find(params[:server_id])
		content = @server.banner.read
		if stale?(etag: content, last_modified: @server.updated_at, public: true)
			send_data content, type: @server.banner.file.content_type, disposition: "inline"
			expires_in 0, public: true
		end
	end

	private
	def server_params
		params.require(:server).permit(:twitter, :facebook, :reddit, :youtube, :website, :steam, :tags, :tag_string, :banner, :banner_cache, :slots, :title, :ip, :port, :pvp, :info, :gold, :country, :version, :difficulty, :sync, :map)
	end
end

app/views/servers/_form.html.haml
= form_for @server, html: {multipart: true} do |f|
  = render 'partials/errors', object: @server
  .row
    %h2 Server Information
    %hr
    .col-md-4
      %p
        = f.label :title
        %br/
        = f.text_field :title, class: 'form-control'
      %p
        = f.label :ip, 'IP Address'
        %br/
        = f.text_field :ip, class: 'form-control', placeholder: "External Server IP"
    .col-md-4
      %p
        = f.label :port
        %br/
        = f.text_field :port, class: 'form-control', value: 25444
      %p
        = f.label :country
        %br/
        = country_select("server", "country", {}, {class: 'form-control'})
    .col-md-4
      %p
        = f.label :slots
        %br/
        = f.text_field :slots, class: 'form-control', value: 8
      %p
        = f.label :version
        %br/
        = f.select :version, options_for_select([["2.2.4", "2.2.4"], ["2.2.5", "2.2.5"]]), {}, class: "form-control"
  .row
    %h2
      Tags
      %small Minimum of 1, Maximum of 5
    %p
      = f.label :tag_string, "Tags"
      = f.text_field :tag_string, class: 'form-control', id: "tags-box", placeholder: 'Enter tags here...', style: "width: 60%;", autocomplete: "off", value: @server.tag_text
      :javascript
        tagsComplete(#{raw Server.valid_tags.as_json}, "#tags-box")
      .help-block Seperate tags with a comma.
  .row
    %h2 
      Social Media
      %small (Not Required)
    %hr
    .col-md-4
      %p
        = f.label :twitter
        = f.text_field :twitter, class: 'form-control'
      %p
        = f.label :facebook
        %br/
        = f.text_field :facebook, class: 'form-control'
    .col-md-4
      %p
        = f.label :website
        %br/
        = f.text_field :website, class: 'form-control'
      %p
        = f.label :steam
        %br/
        = f.text_field :steam, class: 'form-control'
    .col-md-4
      %p
        = f.label :youtube
        %br/
        = f.text_field :youtube, class: 'form-control'
      %p
        = f.label :reddit
        %br/
        = f.text_field :reddit, class: 'form-control'
  .row
    .col-md-12
      %h2 Server Banner
      %hr
      %p
        = f.label :banner
        %br/
        = f.file_field :banner
        = f.hidden_field :banner_cache, value: @server.banner_cache
        .help-block A 468x60 Image for the server banner.
  .row
    .col-md-12
      %h2 Server Description
      %hr
      %p
        = f.label :info, 'Description'
        %br/
        = f.text_area :info, class: 'form-control wysihtml5', :rows => "10", :cols => "10", id: 'description'
        .help-block You may use the editor above to help with the formatting of your server description.
  .row
    .col-md-12
      = f.submit "Submit", class: "btn btn-primary"

app/views/servers/display.js.erb
document.write("<iframe frameborder='0' marginheight='0' width='<%= @width %>' height='<%= @height %>' src='<%= server_embed_url(@server, size: params[:size], color: params[:color], type: params[:type]) %>' id='vote-frame' scrolling='no'></iframe>")

app/views/servers/edit.html.haml
- content_for :title do "Editing #{@server.title}" end
- content_for :head do
  %meta{:content => "Editing Unturned Server", :name => "description"}
  %meta{:content => "Unturned, Servers, Edit", :name => "keywords"}
.page-header
  %h1 
    Editing:
    %small= @server.title
    .pull-right
      .btn-group
        = link_to 'Cancel', servers_path, class: 'btn btn-danger'
= render 'form'

app/views/servers/index.html.haml
- content_for :title do 'Servers' end
- content_for :head do
  %meta{:content => "Unturned Servers List", :name => "description"}
  %meta{:content => "Unturned, Servers, Game, List, Tags, Sort", :name => "keywords"}
.page-header
  .pull-right
    .form-inline
      = form_tag(search_path, :method => :post) do
        = text_field_tag :search, params[:search], class: 'form-control'
        = submit_tag "Search", name: nil, class: "btn btn-primary"
  %h1 Server Listings

.alert.alert-success 
  Welcome to Unturned ServerZ! Feel free to look around and find a server that fits your needs!
  Make sure to share Unturned ServerZ with your friends to help us grow!
  %span.st__hcount{:displaytext => ""}
  %span.st_fblike_hcount{:displaytext => "Facebook Like"}
  %span.st_plusone_hcount{:displaytext => "Google +1"}
  %script{:src => "http://w.sharethis.com/button/buttons.js", :type => "text/javascript"}
  :javascript
    stLight.options({publisher: "c2e6e60e-c42d-4a9b-a6c5-0ca8e2f39a96", doNotHash: false, doNotCopy: false, hashAddressBar: false});
/ - ori = @servers

/ - @servers = @sponsored
/ %h2 Sponsored Servers
/ %hr
/ = render 'partials/servers'
/ - unless @servers.any?
/   #none 
/     Want to buy a slot?
/     %a{href: "#contact", "data-toggle" => 'modal'}
/       Contact us!

/ - @servers = ori
%h2 Unturned Servers
%hr
= render 'partials/servers'

app/views/servers/new.html.haml
- content_for :head do
  %meta{:content => "New Unturned Server", :name => "description"}
  %meta{:content => "Servers, Unturned, New, Create", :name => "keywords"}
- content_for :title do 'New Server' end
.page-header
  %h1 
    New Server
    .pull-right
      .btn-group
        = link_to 'Cancel', servers_path, class: 'btn btn-danger'

= render 'form'

app/views/servers/show.html.haml
- content_for :title do @server.title end
- content_for :head do
  %meta{:content => "Unturned Server - #{@server.title}", :name => "description"}
  %meta{:content => "Servers, Unturned, Server, #{@server.tags.distinct(:text).join(", ")}", :name => "keywords"}
  %meta{:content => "#{@server.user ? @server.user.username : 'Guest'}", :name => "author"}
.page-header
  - if can_manage(@server)
    .pull-right
      .btn-group 
        %button.btn.btn-primary.dropdown-toggle{"data-toggle" => 'dropdown'}
          Manage
          %span.caret
        %ul.dropdown-menu{role: "menu", id: "left-dropdown"}
          %li= link_to 'Edit', edit_server_path(@server)
          %li= link_to 'Delete', server_path(@server), method: :delete, data: {confirm: 'Are you sure you want to delete this server?'}
          %li= link_to 'Reports', server_reports_path(@server)
          %li
            %a{:href => "#contact", "data-toggle" => 'modal'} Sponsor
  %h1= @server.title
.container
  .row
    .col-md-12
      .div.text-center
        .btn-group
          - if current_user and current_user.has_favored(@server)
            = link_to '<i class="fa fa-heart"></i> Unfavor'.html_safe, server_favorite_path(@server, current_user.favorite_for(@server)), class: 'btn btn-danger', rel: "tooltip", title: "Remove this server from your favorites", method: :delete
          - else
            = link_to '<i class="fa fa-heart"></i> Favorite'.html_safe, new_server_favorite_path(@server), class: 'btn btn-danger', rel: "tooltip", title: "Add this server to your favorites"
          %a.btn.btn-success{href: server_vote_path(@server), rel: "tooltip", title: "Vote for this server."}
            %i.fa.fa-thumbs-up
            Vote
          %button.btn.btn-primary{"data-target" => "#connect-modal", "data-toggle" => "modal", rel: "tooltip", title: "Learn how to connect to this server."} 
            %i.fa.fa-play
            Connect
          #connect-modal.modal.fade{:role => "dialog", :tabindex => "-1"}
            .modal-dialog
              .modal-content
                .modal-header
                  %button.close{"data-dismiss" => "modal", :type => "button"}
                    %span{"aria-hidden" => "true"} ×
                    %span.sr-only Close
                  %h4.modal-title{style: 'text-align: left;'} Connecting
                .modal-body{style: 'text-align: left;'}
                  To connect to an Unturned Server follow these steps:
                  %ol
                    %li 
                      Open 
                      %a{href: "steam://rungameid/304930"} Unturned 
                      and select Play.
                    %li Click 'Connect.'
                    %li 
                      Set the port to 
                      %strong '#{@server.port}'
                    %li 
                      Set the IP Address to 
                      %strong '#{@server.ip}'
                    %li Click 'Connect.'
                .modal-footer
                  %button.btn.btn-danger{"data-dismiss" => "modal", :type => "button"} Close
          %a.btn.btn-danger{href: new_server_report_path(@server), rel: "tooltip", title: "Report an issue with this server."}
            %i.fa.fa-flag
            Report
  .row
    .col-md-12
      .text-center{style: "margin-top: 5px"}
        - if @server.steam != nil and @server.steam != ""
          %a.social{href: "http://steamcommunity.com/groups/#{@server.steam}", rel: "tooltip", title: "Server Steam Group", data: {placement: "top"}}
            %i.fa.fa-steam-square.social-media{style: "color: black;"}
        - if @server.facebook != nil  and @server.facebook != ""
          %a.social{href: "#{@server.facebook}", rel: "tooltip", title: "Server Facebook Page", data: {placement: "top"}}
            %i.fa.fa-facebook-square.social-media{style: "color: blue;"}
        - if @server.twitter != nil and @server.twitter != ""
          %a.social{href: "http://twitter.com/#{@server.twitter}", rel: "tooltip", title: "Server Twitter", data: {placement: "top"}}
            %i.fa.fa-twitter-square.social-media{style: "color: #4099FF;"}
        - if @server.reddit != nil and @server.reddit != ""
          %a.social{href: "http://reddit.com/r/#{@server.reddit}", rel: "tooltip", title: "Server Subreddit", data: {placement: "top"}}
            %i.fa.fa-reddit-square.social-media{style: "color: lightblue;"}
        - if @server.youtube != nil and @server.youtube != ""
          %a.social{href: "https://www.youtube.com/user/#{@server.youtube}", rel: "tooltip", title: "Youtube Channel", data: {placement: "top"}}
            %i.fa.fa-youtube-square.social-media{style: "color: #FF0202;"}
        - if @server.website != nil and @server.website != ""
          %a.social{href: @server.website, rel: "tooltip", title: "Server Website", data: {placement: "top"}}
            %i.fa.fa-html5.social-media
        :javascript
          $('.social').tooltip();
  - if @server.banner?
    .row
      .col-md-12
        .text-center
          %div{style: 'margin-top: 15px;'}
            = image_tag server_banner_url(@server), width: '468', height: '60'
  .row-fluid
    .col-md-6
      %h2 Server Information
      %hr
      %table.table.table-bordered{style: "font-size: 15px;"}
        %tbody
          %tr
            %td 
              %i.fa.fa-arrow-circle-up
              IP Address
            %td
              %span{id: 'server-ip', "data-clipboard-text" => @server.ip, rel: "tooltip", title: "Click to copy to clipboard.", href: "#", data: {placement: "top"}}= @server.ip
              :javascript
                var client = new ZeroClipboard(document.getElementById("server-ip"));
                $("#server-ip").tooltip();
          %tr
            %td
              %i.fa.fa-arrow-circle-up
              Port
            %td= @server.port
          %tr
            %td 
              %i.fa.fa-history
              Version
            %td{style: "vertical-align: middle;"}
              %a.no-deco{href: version_path(@server.version.gsub(".", "-"))}
                %span.label.label-primary{style: "vertical-align: middle; font-size: 14px;"}= @server.version
          %tr
            %td 
              %i.fa.fa-list-ol
              Slots
            %td= @server.slots
          %tr
            %td
              %i.fa.fa-tag
              Tags
            %td{style: "width: 65%"}
              .div
                - @server.tags.each do |tag|
                  %a.tag{href: tag_path(tag.text)}
                    %span.badge{style: "display: inline-block;"}=tag.text
          %tr
            %td 
              %i.fa.fa-user
              Owner
            %td
              - if @server.user
                = link_to @server.user.username, user_path(@server.user.username), class: 'no-deco'
              - else
                Guest
          %tr
            %td
              %i.fa.fa-location-arrow
              Location
            %td{style: "vertical-align: middle;"}
              %a{href: country_path(@server.country), id: @server.country, alt: @server.country_name}
                %span=@server.get_flag
              %span{style: "vertical-align: middle;"}= @server.country_name
          %tr
            %td 
              %i.fa.fa-calendar-o
              Registered
            %td{style: "vertical-align: middle;"}
              .label.label-default= time_ago_in_words(@server.created_at) + ' ago'
          %tr
            %td
              %i.fa.fa-calendar
              Updated
            %td{style: "vertical-align: middle;"}
              .label.label-default= time_ago_in_words(@server.updated_at) + ' ago'
      %h2 Embeddable Buttons
      %hr
      .div
        %p
          .inline-form
            %a.btn{class: "btn-primary", href: server_vote_url(@server), target: '_blank'} Vote on Unturned ServerZ
            %a.btn.btn-default.btn-sm{data: {toggle: "collapse", target: "#code1"}} Code
          %textarea.collapse.form-control{rows: 3, id: "code1"}= "<script src='#{server_display_url(@server)}'></script>"
        %p
          .inline-form
            %a.btn{class: "btn-primary btn-sm", href: server_vote_url(@server), target: '_blank'} Vote on Unturned ServerZ
            %a.btn.btn-default.btn-sm{data: {toggle: "collapse", target: "#code2"}} Code
          %textarea.collapse.form-control{rows: 3, id: "code2"}= "<script src='#{server_display_url(@server, size: "small")}'></script>"
        %p
          .inline-form
            %a.btn{class: "btn-primary", href: new_server_favorite_url(@server), target: '_blank'} Like on Unturned ServerZ
            %a.btn.btn-default.btn-sm{data: {toggle: "collapse", target: "#code3"}} Code
          %textarea.collapse.form-control{rows: 3, id: "code3"}= "<script src='#{server_display_url(@server, type: "favorites")}'></script>"
        %p
          .inline-form
            %a.btn{class: "btn-primary btn-sm", href: new_server_favorite_url(@server), target: '_blank'} Like on Unturned ServerZ
            %a.btn.btn-default.btn-sm{data: {toggle: "collapse", target: "#code4"}} Code
          %textarea.collapse.form-control{rows: 3, id: "code4"}= "<script src='#{server_display_url(@server, type: "favorites", size: "small")}'></script>"
    .col-md-6{id: "stats-col"}
      %h2 Statistics
      %hr
      %table.table.table-bordered{style: "font-size: 15px;"}
        %tbody
          %tr
            %td{style: 'width: 50%'}
              %i.fa.fa-heart
              Favorites
            %td= @server.favorites.size
          %tr  
            %td{style: 'width: 50%'}
              %i.fa.fa-thumbs-up
              Votes
            %td= @server.votes.size
          %tr
            %td{style: 'width: 50%'} 
              %i.fa.fa-eye
              Views
            %td 0
      .text-center
        %h3 Graphed Statistics
        .tabbable
          %ul.nav.nav-tabs
            %li.tab-pane.active
              %a{"data-toggle" => "tab", href: "#voting"} Voting
            %li.tab-pane
              %a{"data-toggle" => "tab", href: "#favorites"} Favorites
          .tab-content{style: "overflow: visible;"}
            .tab-pane.active{id: "voting"}
              %canvas{id: 'votes-chart', height: "350"}
            .tab-pane{id: "favorites"}
              %canvas{id: 'favorites-chart', height: "350"}

        - today = Time.now
        :javascript
          var labels = ["#{(today - 6.day).strftime("%A")}", "#{(today - 5.day).strftime("%A")}", "#{(today - 4.day).strftime("%A")}", "#{(today - 3.day).strftime("%A")}", "#{(today - 2.day).strftime("%A")}", "#{(today - 1.day).strftime("%A")}", "#{today.strftime("%A")}"]
          displayChart("votes-chart", labels, getData("votes"), "votes");
          displayChart("favorites-chart", labels, getData("favorites"), "favorites");

          function getData(type) {
            var data = [];
            if (type == "favorites") {
              data = [#{get_time(@server, 6, "favorites")}, #{get_time(@server, 5, "favorites")}, #{get_time(@server, 4, "favorites")}, #{get_time(@server, 3, "favorites")}, #{get_time(@server, 2, "favorites")}, #{get_time(@server, 1, "favorites")}, #{get_time(@server, 0, "favorites")}]
            } else if (type == "votes") {
              data = [#{get_time(@server, 6, "votes")}, #{get_time(@server, 5, "votes")}, #{get_time(@server, 4, "votes")}, #{get_time(@server, 3, "votes")}, #{get_time(@server, 2, "votes")}, #{get_time(@server, 1, "votes")}, #{get_time(@server, 0, "votes")}]
            }
            return data;
          }
      %h2 
        Share
        %small 
          Promote This Server
      %hr
      %span.st_facebook_large{:displaytext => "Facebook"}
      %span.st_googleplus_large{:displaytext => "Google +"}
      %span.st_twitter_large{:displaytext => "Tweet"}
      %span.st_email_large{:displaytext => "Email"}       
  .row
    .col-md-12
      %h2 Description
      %hr
      = simple_format(@server.info)
  .row
    .col-md-12
      %h2 
        Comments
        .pull-right
          .btn.btn-primary.btn-sm{id: 'click-btn'} Add Comment
      %hr
      - if current_user
        %div{id: 'show-form', show: false}
          = render 'comments/form'
        :javascript
          $("#show-form").toggle("show"); 
          $("#click-btn").click(function() {
            if ($("#show-form").is(":visible")) {
              $("#click-btn").text("Add Comment")
            } else {
              $("#click-btn").text("Hide")
            } 
            $("#show-form").toggle("show"); 
          }); 
      - if @server.comments.select { | comment | comment.valid? }.any?
        = render 'comments/view'
      - else
        #none No comments have been posted yet.
:javascript
  var switchTo5x=true;
%script{:src => "http://w.sharethis.com/button/buttons.js", :type => "text/javascript"}
:javascript
  stLight.options({publisher: "c2e6e60e-c42d-4a9b-a6c5-0ca8e2f39a96", doNotHash: true, doNotCopy: true, hashAddressBar: false});

app/views/servers/vote.html.haml
- content_for :head do
  %meta{:content => "Voting for #{@server.title}", :name => "description"}
  %meta{:content => "Servers, Unturned, Server, Vote", :name => "keywords"}
  %meta{:content => "#{@server.user.username}", :name => "author"}
- content_for :title do 'Voting' end
.page-header
  %h1
    Voting for:
    %small
      = @server.title
    .pull-right
      .btn-group
        = link_to 'Back', @server, class: 'btn btn-danger'

= form_tag server_cast_vote_path(@server), method: 'post' do
  %p
    .form-inline
      .text-center
        = text_field :form, :captcha, :placeholder => 'What is the main enemy in Unturned?', class: 'form-control', style: 'width: 25%'
        = submit_tag 'Vote', class: 'btn btn-primary', data: { disable_with: "Voting..." }
        .help-block Enter the name of the main enemy in Unturned to vote.