config/routes.rb
Rails.application.routes.draw do
  root "servers#index"
  ActiveAdmin.routes(self)
  post '/contact', :to => "application#contact"
  get '/tag/:tag', :to => "servers#index", :as => "tag"
  get '/version/:version', :to => "servers#index", :as => "version"
  get '/country/:country', :to => "servers#index", :as => "country"
  get '/api', :to => "resources#api", :as => "api"
  get '/terms', :to => "resources#terms", :as => "terms"
  get '/stats', :to => "application#stats", :as => "stats"
  get '/user/:username', :to => "application#user", :as => "user"
  get '/favorites', :to => "application#favorites", :as => "favorites"
  post '/search(/:search)', :to => "servers#search", :as => "search"
  get '/countries', :to => "application#countries", :as => "countries"
  get '/tags', :to => "application#tags", :as => "tags"
  get '/versions', :to => "application#versions", :as => "versions"
  get '/sponsored', :to => "application#sponsored", :as => "sponsored"
  get '/resources/sponsored', :to => "resources#sponsored", :as => "sponsored_resource"
  devise_for :users, :controllers => { :registrations => "registrations" }
  resources :servers do
    resources :comments
    resources :reports
    resources :favorites do
      post :favor
    end
    post :cast_vote
    get :vote
    get :banner
    get :embed
    get :display
  end
  resources :revisions
  resources :articles
  get 'ping' => proc {|env| [200, {}, []] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?
  include ApplicationHelper
  
  def authenticate_admin_user!
    redirect_to root_path unless require_admin
  end

  def contact
    form = params[:contact]
    username = form[:username]
    email = form[:email]
    question = form[:question]
    return redirect_to root_path, notice: 'Please make sure to fill all fields.' if username == nil or email == nil or question == nil
    UserMailer.contact(email, username, question).deliver
    return redirect_to root_path, notice: 'Successfully submitted an inquiry.'
  end

  def user
    @user = User.where(:username => params[:username]).first
    @servers = Server.where(:user => @user).page(params[:page])
  end

  def stats
    @servers = Server.all
    @user = User.all
  end

  def sponsored
    @servers = Server.where(:sponsored => true)
  end

  def favorites
    return redirect_to root_path, :notice => "You must be signed in to view your favorites." if not current_user
    favs = current_user.favorites
    @servers = Array.new
    favs.each do |fav|
      @servers << fav.server
    end
    @servers = Kaminari.paginate_array(@servers).page(params[:page])
  end

  def countries
    @countries = Server.distinct(:country)
  end

  def tags
    @tags = Tag.gt(count: 0)
  end

  def versions
    @versions = Server.distinct(:version)
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) do |u|
      u.permit(:steam, :twitter, :youtube, :facebook, :skype, :reddit, :github, :twitch, :newsletter, :username, :email, :password, :password_confirmation)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def get_time(server, subtract, type)
    case type
    when "votes"
      return server.votes.all.where(created_at: ((Time.now - subtract.day).beginning_of_day..(Time.now - subtract.day).end_of_day)).to_a.size
    when "favorites"
      return server.favorites.all.where(created_at: ((Time.now - subtract.day).beginning_of_day..(Time.now - subtract.day).end_of_day)).to_a.size
    end
  end

  def country_name(abbr)
    country = ISO3166::Country[abbr]
    country.translations[I18n.locale.to_s] || country.name
  end

  def require_admin
    current_user and current_user.admin?
  end

  def can_manage(server)
    current_user and (current_user.admin? or server.user == current_user)
  end

  def set_active(controller)
    return params[:controller] == controller ? "active" : ""
  end

  def tag_cloud(classes)
    tags = Tag.all.to_a.map{ |r| [r["text"], r["count"]] }
    max = tags.sort_by(&:count).last
    tags = tags.shuffle
    tags.each do |tag|
      if tag[1] == 0 and max[1] == 0
        index = 0
      else
        index = tag[1].to_f / max[1] * (classes.size - 1)
      end
      yield(tag, classes[index])
    end
  end

  def get_countries
    countries = Server.distinct(:country)
    data = Array.new
    countries.each do |country|
      count = Server.where(:country => country).size
      country_hash = Hash.new
      country_hash['value'] = count
      country_hash['label'] = country
      country_hash['color'] = random_color
      country_hash['highlight'] = random_color
      data << country_hash
    end
    data
  end

  def get_versions
    versions = Server.distinct(:version)
    data = Array.new
    versions.each do |version|
      count = Server.where(:version => version).size
      version_hash = Hash.new
      version_hash['value'] = count
      version_hash['label'] = version
      version_hash['color'] = random_color
      version_hash['highlight'] = random_color
      data << version_hash
    end
    data
  end

  def random_color(hash = true)
    color = "%06x" % (rand * 0xffffff)
    if hash
      return "#" + color
    else
      return color
    end
  end
end

app/views/application/countries.html.haml
- content_for :title do 'By Country' end
- content_for :head do
  %meta{:content => "Unturned Servers by Country", :name => "description"}
  %meta{:content => "Servers, Unturned, Countries, Sort", :name => "keywords"}
.page-header
  %h1 
    Servers by Country
    .pull-right
      = link_to 'Back', servers_path, class: 'btn btn-primary'

#none Want to find a server in your own country? Only the top server in each country is shown here but, each header links to more servers in the same country!

- @countries.each do |country|
  %h2= link_to country_name(country), country_path(country)
  %hr
  - @servers = Server.where(:country => country).desc("vote_count").limit(1).to_a
  - @servers = Kaminari.paginate_array(@servers).page(params[:page])
  = render 'partials/servers'

app/views/application/favorites.html.haml
- content_for :head do
  %meta{:content => "Favorite Unturned Servers", :name => "description"}
  %meta{:content => "Servers, Unturned, Favorites, Liked", :name => "keywords"}
- content_for :title do 'My Favorites' end
.page-header
  %h1 Your Favorites

= render 'partials/servers'

app/views/application/sponsored.html.haml
- content_for :title do 'Sponsored Servers' end
- content_for :head do
  %meta{:content => "Sponsored Unturned Servers", :name => "description"}
  %meta{:content => "Servers, Unturned, Sponsored", :name => "keywords"}
.page-header
  %h1 
    Sponsored Servers
    .pull-right
      = link_to 'Back', servers_path, class: 'btn btn-primary'

.alert.alert-success
  %i.fa.fa-usd
  Want to buy a slot?
  %a.alert-link{href: "#contact", "data-toggle" => 'modal'}
    Contact us!

= render 'partials/servers'

app/views/application/stats.html.haml
- content_for :title do 'Website Stats' end
- content_for :head do
  %meta{:content => "Unturned ServerZ Site Stats", :name => "description"}
  %meta{:content => "Servers, Unturned, Stats, Web", :name => "keywords"}
.page-header
  %h1 Site Stats

.row
  .col-md-6{id: "locations-canvas"}
    %h2 Server Locations
    %hr
    %canvas{id: 'server-locations', height: "350"}
  .col-md-6{id: "versions-canvas"}
    %h2 Server Versions
    %hr
    %canvas{id: 'server-versions', height: "350"}

:javascript
  var location_data = #{get_countries.to_json}
  var width = $("#locations-canvas").width();
  var canvas = document.getElementById("server-locations");
  var ctx = canvas.getContext("2d");
  ctx.canvas.width = width;
  var locationChart = new Chart(ctx).Pie(location_data);
  locationChart.update();

  var version_data = #{get_versions.to_json}
  var width1 = $("#versions-canvas").width();
  var canvas1 = document.getElementById("server-versions");
  var ctx1 = canvas1.getContext("2d");
  ctx1.canvas.width = width1;
  var versionChart = new Chart(ctx1).Pie(version_data);
  versionChart.update();

app/views/application/tags.html.haml
- content_for :title do 'By Tag' end
- content_for :head do
  %meta{:content => "Unturned Servers by Tag", :name => "description"}
  %meta{:content => "Servers, Unturned, Tag, Sort", :name => "keywords"}
.page-header
  %h1 
    Servers by Tag
    .pull-right
      = link_to 'Back', servers_path, class: 'btn btn-primary'

- if not @tags.any?
  #none No tags are currently being used by any servers.
- else
  - @tags.each do |tag|
    %h2= link_to tag.text, tag_path(tag.text)
    %hr
    - @servers = tag.servers.limit(1).desc("vote_count").to_a
    - @servers = Kaminari.paginate_array(@servers).page(params[:page])
    = render 'partials/servers'

.row
  .col-md-12
    #tag_cloud.center-block{style: "text-align: center;"}
      - tag_cloud(%w{s m l}) do |tag, css_class|
        .badge{class: css_class}= link_to tag[0], tag_path(tag[0]), class: 'no-deco'

app/views/application/user.html.haml
- content_for :title do "#{@user.username}" end
- content_for :head do
  %meta{:content => "Unturned ServerZ profile for #{@user.username}", :name => "description"}
  %meta{:content => "Servers, Unturned, User, Profile", :name => "keywords"}
.page-header
  %h1= @user.username

.container
  .row
    %h2 Statistics
    %hr
    .col-md-3
      %strong= time_ago_in_words(@user.created_at) + " ago"
      %small Registered
    .col-md-3
      %strong= @servers.size
      %small Servers
    .col-md-3
      %strong= @user.favorites.size
      %small Favorites
    .col-md-3
      %strong= @user.votes.size
      %small Votes

  .row
    %h2 Contact Information
    %hr
    - if @user.steam != ""
      .col-md-3
        %label 
          %strong Steam
        .well.well-sm{style: "width: 75%"}
          %a{href: "http://steamcommunity.com/groups/#{@user.steam}"}= @user.steam
    - if @user.twitter != ""
      .col-md-3
        %label
          %strong Twitter
        .well.well-sm{style: "width: 75%"}
          %a{href: @user.twitter}= @user.twitter
    - if @user.youtube != ""
      .col-md-3
        %label 
          %strong Youtube
        .well.well-sm{style: "width: 75%"}
          %a{href: "http://youtube.com/#{@user.youtube}"}= @user.youtube
    - if @user.facebook != ""
      .col-md-3
        %label 
          %strong Facebook
        .well.well-sm{style: "width: 75%"}
          %a{href: @user.facebook}= @user.facebook
    - if @user.skype != ""
      .col-md-3
        %label 
          %strong Skype
        .well.well-sm{style: "width: 75%"}
          %a{href: "skype:#{@user.skype}?userinfo"}= @user.skype
    - if @user.reddit != ""
      .col-md-3
        %label 
          %strong Reddit
        .well.well-sm{style: "width: 75%"}
          %a{href: "http://reddit.com/u/#{@user.reddit}"}= @user.reddit
    - if @user.github != ""
      .col-md-3
        %label 
          %strong Github
        .well.well-sm{style: "width: 75%"}
          %a{href: "http://github.com/#{@user.github}"}= @user.github
    - if @user.twitch != ""
      .col-md-3
        %label 
          %strong Twitch
        .well.well-sm{style: "width: 75%"}
          %a{href: "http://twitch.tv/#{@user.twitch}"}= @user.twitch
  .row
    .col-md-12
      %label
        %strong About Me:
      .well= @user.about

  .row
    %h2 Servers
    %hr
    = render 'partials/servers'

app/views/application/versions.html.haml
- content_for :title do 'By Version' end
- content_for :head do
  %meta{:content => "Unturned Servers by Version", :name => "description"}
  %meta{:content => "Servers, Unturned, Versions, Sort", :name => "keywords"}
.page-header
  %h1 
    Servers by Version
    .pull-right
      = link_to 'Back', servers_path, class: 'btn btn-primary'

- @versions.each do |version|
  %h2= link_to version, version_path(version.gsub(".", "-"))
  %hr
  - @servers = Server.where(:version => version).limit(1).desc("vote_count").to_a
  - @servers = Kaminari.paginate_array(@servers).page(params[:page])
  = render 'partials/servers'